### PR TITLE
refactor

### PR DESCRIPTION
**Pull request by sunny-g**

### CODE REVIEW

**Comment by vmx** [comment]
Cool to see that you're back working on it. I just want to mention that recently https://github.com/ipfs-rust/libipld gained some IPLD Schema related things. There isn't much documentation, though you might want to have a look at the source.

**Comment by sunny-g** [comment]
@vmx thanks, its good to be back :) Appreciate the update - where is it exactly?

**Comment by vmx** [comment]
@sunny-g have a look at the tests: https://github.com/ipfs-rust/libipld/tree/b8e65591f6e1e3035c9440c2b5cb1ef3e09b3373/dag-cbor-derive/tests

**Comment by vmx** [comment]
@sunny-g it might be of interest for you that the newest version if libipld also has Serde support and there's even a DAG-CBOR Serde based codec now at https://github.com/ipld/serde_ipld_dagcbor (it would be great to have e.g. also a proper DAG-JSON one).

I case you have your own codec and want to test if they are spec compliant, we have quite a few test fixtures we test our implementations against: https://github.com/ipld/codec-fixtures

**Comment by sunny-g** [comment]
@vmx thanks for the keeping me in the loop! I never intended to write my own codecs, instead opting to use the existing `serde_json` and `serde_cbor` codecs + rust nightly to glue it all together, and just pushed some changes that seemed to fix some lingering round trip bugs.

I'll definitely incorporate these fixtures though, as I want to be as compliant as possible. On that note, I noticed [this change](https://github.com/multiformats/rust-cid/blob/master/src/serde.rs#L34) in the latest `cid` library re: serde: isn't this a deviation from the spec? Has something changed wrt to encoding links recently?

**Comment by vmx** [comment]
> I'll definitely incorporate these fixtures though, as I want to be as compliant as possible. On that note, I noticed [this change](https://github.com/multiformats/rust-cid/blob/master/src/serde.rs#L34) in the latest `cid` library re: serde: isn't this a deviation from the spec? Has something changed wrt to encoding links recently?

This is a hack in order to make our codecs to recognize CIDs. It's similar to what [`serde_json` does for arbitrary precision numbers](https://github.com/serde-rs/json/blob/44d9c53e2507636c0c2afee0c9c132095dddb7df/src/number.rs#L17-L18). You define some unique struct and when you see it, your custom (de)serializers know what to do. This of course means that it doesn't work well with generic ones.

This way we can deserialize directly into a rust-cid CID.

**Comment by sunny-g** [comment]
@vmx Good news - my latest changes eliminate the need for the nightly compiler, and still let us use `serde-*` libraries untouched! This required the introduction of alternatives to the `Serialize::serialize` and `Deserialize::deserialize` methods, as well as some use of const generics, but it works!

If you want to hop on a quick call sometime so I can explain it, let me know!

**Comment by vmx** [comment]
Oh cool, I'll try to find some time to take a closer look.

What might be interesting for you could be the every two weeks IPLD call (which I'm also usually at). There folks talk about all things IPLD, so you'd be more then welcome to talk about your IPLD implementation. For details about the call see https://github.com/ipld/team-mgmt#every-two-weeks-call.

**Comment by vmx** [comment]
I had a quick look. I'd be interesting in some code using all this.

Some other random comments:
 - For the Serde based things, I decided to go for https://github.com/quininer/cbor4ii instead of Ciborium. So far I'm quite happy with cbor4ii.
 - I wonder if you could directly use https://github.com/ipld/serde_ipld_dagcbor instead of Ciborium/cbor4ii, that might reduce a bit of the code
 - I had to remove https://github.com/datalove-app/ipld/blob/fac361dc688bfca34c782ba9b35a63d7aff8973f/src/codecs/mod.rs#L9-L10 in order to compile it

**Comment by sunny-g** [comment]
@vmx ah sorry about that - still a major WIP so I have a lot of uncommitted things laying around.

re: serde-cbor alternatives - that's awesome, I haven't paid too much attention and don't have strong feelings about which one to use, aside from that I don't want to write and maintain one myself :P so I'll take a look and make some kind of switch soon.

re: using serde_ipld_dagcbor - that's an equally good idea, but again for me more depends on longevity and how active y'all want to be in maintaining it.

re: bi-weekly call - I'd love that! I hope that even though the library is still a major WIP and is more a breadth-first than depth-first attempt at implementing a lot of IPLD, that people would still be happy to see what I have so far.

**Comment by vmx** [comment]
> re: using serde_ipld_dagcbor - that's an equally good idea, but again for me more depends on longevity and how active y'all want to be in maintaining it.

That will be maintained for the foreseeable future. It's core part of the Filecoin Virtual Machine. And even in case that library is dropped, there will be a suitable replacement.

**Pull request merged**
